auth:
    username: ''
    password: ''

email:
    subject: 'Dagens Horoskop'
    sender_alias: 'Dina Dagliga Horoskop'
    recipients:

horoscopes:
    - website_name: 'Twice'
      website_url: 'http://www.dagenshoroskop.nu/horoskop/dagens/11/'
      text_xpath: '(//p)[2]'
